feat: test sealights ginkgo plugin

diff --git a/integration-tests/pipelines/sealights-e2e.yaml b/integration-tests/pipelines/sealights-e2e.yaml
--- a/integration-tests/pipelines/sealights-e2e.yaml
+++ b/integration-tests/pipelines/sealights-e2e.yaml
@@ -159,7 +159,13 @@ spec:
 
               slcli scan --tests-runner --enable-ginkgo --workspacepath "$(pwd)/tests/e2e" --path-to-scanner /usr/local/bin/slgoagent --scm none
 
-              # Install Ginkgo
-              go install github.com/onsi/ginkgo/v2/ginkgo@latest
-
-              cd tests/e2e && ginkgo --json-report=report.json
+              # Execute the upload script
+              UPLOAD_SCRIPT="${PWD}/upload_it_plugin.sh"
+              if [[ -x "$UPLOAD_SCRIPT" ]]; then
+                echo "INFO: Running upload script: '$UPLOAD_SCRIPT'"
+                /bin/bash "$UPLOAD_SCRIPT"
+                echo "INFO: Upload script completed successfully."
+              else
+                echo "ERROR: Upload script '$UPLOAD_SCRIPT' not found or not executable."
+                exit 1
+              fi
